# Generated by Django 3.0.5 on 2020-05-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20200510_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Ready'), ('P', 'Picked'), ('D', 'Delivered')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='city',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='restaurants.Wilaya'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='restaurants.Order'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='images',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurantcuisines',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuisines', to='restaurants.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantmealtypes',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meal_types', to='restaurants.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restauranttypes',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='types', to='restaurants.Restaurant'),
        ),
    ]
