# Generated by Django 3.0.5 on 2020-05-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20200511_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='offered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menus', to='restaurants.Restaurant'),
        ),
    ]
