# Generated by Django 3.0.5 on 2020-06-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20200528_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='menus', to='restaurants.Cuisine'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menus', to='restaurants.OfferType'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menus', to='restaurants.MealType'),
        ),
    ]
