# Generated by Django 3.0.5 on 2020-06-02 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20200601_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='close_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{,12}$', "The phone number you entered is not valid it must be of the international format.example '+213799136332'", 'Invalid PhoneNumber')]),
        ),
    ]
