# Generated by Django 3.0.5 on 2020-06-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20200606_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(through='restaurants.RestaurantCuisines', to='restaurants.Cuisine'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='meal_types',
            field=models.ManyToManyField(through='restaurants.RestaurantMealTypes', to='restaurants.MealType'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='types',
            field=models.ManyToManyField(through='restaurants.RestaurantTypes', to='restaurants.RestaurantType'),
        ),
        migrations.AlterField(
            model_name='restaurantcuisines',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantmealtypes',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restauranttypes',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Restaurant'),
        ),
    ]
