# Generated by Django 3.0.5 on 2020-06-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20200608_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='on_special_day',
            field=models.BooleanField(default=False),
        ),
    ]
