# Generated by Django 3.0.5 on 2020-06-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_restaurant_on_special_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='global_discount',
            field=models.FloatField(default=0),
        ),
    ]
