# Generated by Django 3.0.5 on 2020-06-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_restaurant_global_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
