# Generated by Django 3.0.5 on 2020-06-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_orderline_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Ready'), ('Pi', 'Picked'), ('D', 'Delivered')], default='P', max_length=2),
        ),
    ]
