# Generated by Django 3.0.5 on 2020-07-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_auto_20200709_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
