# Generated by Django 3.0.5 on 2020-04-18 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryguy',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_guy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryguy',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.VehicleType'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Address'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.DeliveryGuy'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Order'),
        ),
    ]
