# Generated by Django 3.0.5 on 2020-04-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200419_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='main',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/main'),
        ),
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='step'),
        ),
    ]
