# Generated by Django 3.0.5 on 2020-04-27 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200427_1710'),
        ('recipe', '0007_auto_20200427_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='restaurants.Client'),
        ),
    ]
