# Generated by Django 3.0.5 on 2020-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_customcontains_customingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcontains',
            name='ingredient',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='CustomIngredient',
        ),
    ]
