# Generated by Django 3.0.5 on 2020-04-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20200428_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcontains',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_contains', to='recipe.Recipe'),
        ),
    ]
