# Generated by Django 3.0.5 on 2020-06-16 08:56

from django.db import migrations, models
import django.db.models.deletion
import rating.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0012_auto_20200608_1124'),
        ('delivery', '0002_auto_20200418_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.FloatField(default=0)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Client')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rates', to='restaurants.Restaurant')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rating.models.BaseRestaurantReviews),
        ),
        migrations.CreateModel(
            name='RateMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.FloatField(default=0)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Client')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rates', to='restaurants.Menu')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rating.models.BaseMenuReviews),
        ),
        migrations.CreateModel(
            name='RateDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.FloatField(default=0)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Client')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rates', to='delivery.DeliveryGuy')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rating.models.BaseDeliveryReviews),
        ),
        migrations.CreateModel(
            name='LikeRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Client')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='restaurants.Restaurant')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rating.models.BaseRestaurantReviews),
        ),
        migrations.CreateModel(
            name='LikeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Client')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='restaurants.Menu')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rating.models.BaseMenuReviews),
        ),
        migrations.CreateModel(
            name='LikeDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Client')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='delivery.DeliveryGuy')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rating.models.BaseDeliveryReviews),
        ),
        migrations.CreateModel(
            name='CommentRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Client')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='restaurants.Restaurant')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rating.models.BaseRestaurantReviews),
        ),
        migrations.CreateModel(
            name='CommentMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Client')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='restaurants.Menu')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rating.models.BaseMenuReviews),
        ),
        migrations.CreateModel(
            name='CommentDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.Client')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='delivery.DeliveryGuy')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rating.models.BaseDeliveryReviews),
        ),
    ]
