# Generated by Django 3.0.5 on 2020-07-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedelivery',
            name='like',
        ),
        migrations.RemoveField(
            model_name='likemenu',
            name='like',
        ),
        migrations.RemoveField(
            model_name='likerestaurant',
            name='like',
        ),
    ]
